version: "2"
services:   
  web:      
    build: .
    ports:
      - 8080:8080
    volumes:
      - $PWD/src/main/resources/application.yml:/app/application.yml
    mem_limit: 200m
    cpus: "1"

  db:
    image: novinrepo:8082/docker/bitnami/postgresql
    ports:
      - 5432:5432
    volumes:
      - $PWD/data:/data
    environment:
      - POSTGRES_DB=automobiles
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=123
