apiVersion: v1
kind: Pod
metadata:
  name: pg-db
  namespace: default
  labels:
    app: pg-db
spec:
  containers:
    - name: postgres
      image: novinrepo:8082/docker/bitnami/postgresql
      ports:
        - name: db
          containerPort: 5432
          protocol: TCP
      env:
        - name: POSTGRES_DB
          value: automobiles
        - name: POSTGRESQL_USERNAME
          value: postgres
        - name: POSTGRESQL_PASSWORD
          value: 123
